apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "supertokens.fullname" . }}-pvc
  labels:
    {{- include "supertokens.labels" . | nindent 4 }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: 1Gi